version: '3.8'

services:
  # ==========================================
  # --- PARTIE SOC (SÉCURITÉ ET LOGS) ---
  # ==========================================
  
  mongodb:
    image: mongo:latest
    container_name: chausec-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: superAdmin
      MONGO_INITDB_ROOT_PASSWORD: Chaussec.123
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chaussec_net

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: chausec-opensearch
    restart: unless-stopped
    environment:
      - cluster.name=chausec-cluster
      - node.name=chausec-node1
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - chaussec_net

  graylog:
    image: graylog/graylog:7.1
    container_name: chaussec-graylog
    restart: unless-stopped
    environment:
      - GRAYLOG_PASSWORD_SECRET=UnSecretVraimentTresLongPourChaussec2026!
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://superAdmin:Chaussec.123@mongodb:27017/graylog?authSource=admin
    ports:
      - "9000:9000"
      - "1514:1514/udp"
      - "5044:5044/tcp"
    depends_on:
      - mongodb
      - opensearch
    networks:
      - chaussec_net

  # ==========================================
  # --- PARTIE SONDE ET COLLECTE ---
  # ==========================================

  suricata:
    image: jasonish/suricata:6.0.10
    container_name: chaussec-suricata
    restart: unless-stopped
    network_mode: host
    command: -i eth0
    volumes:
      - suricata_logs:/var/log/suricata

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.12.1
    container_name: chaussec-filebeat
    restart: unless-stopped
    user: root 
    command: ["--strict.perms=false"]
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - suricata_logs:/var/log/suricata:ro
    depends_on:
      - graylog
    networks:
      - chaussec_net

  # ==========================================
  # --- PARTIE SUPERVISION ET DASHBOARDS ---
  # ==========================================

  prometheus:
    image: prom/prometheus:latest
    container_name: chaussec-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - chaussec_net

  grafana:
    image: grafana/grafana:latest
    container_name: chaussec-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      # Injection automatique des sources de données
      - ./config/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      # Injection automatique du provider de tableaux de bord
      - ./config/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      # Injection automatique du fichier JSON du tableau de bord
      - ./config/chaussec-dashboard.json:/etc/grafana/provisioning/dashboards/chaussec-dashboard.json:ro
    networks:
      - chaussec_net
    
  chaussec-api:
    image: scxrrow/backend:latest
    container_name: chaussec-api
    ports:
      - "5050:5050"
    networks:
      - chaussec_net

# ==========================================
# --- VOLUMES ET RÉSEAUX ---
# ==========================================

volumes:
  mongodb_data:
  opensearch_data:
  suricata_logs:

networks:
  chaussec_net:
    driver: bridge