filebeat.inputs:
- type: log
  enabled: true
  paths:
    # Le chemin où Filebeat va aller lire les alertes générées par Suricata
    - /var/log/suricata/eve.json
  # On indique à Filebeat que Suricata écrit en JSON pour qu'il garde la structure
  json.keys_under_root: true
  json.overwrite_keys: true

output.logstash:
  # On envoie le tout directement vers le conteneur Graylog sur le port Beats qu'on a ouvert
  hosts: ["graylog:5044"]